UpstreamData/pyasic

- miners/_backends/btminer.py
When a MAC was already known, it wouldn't be added to the data, since the statement was never reached.
> Fix indent issue that caused missing MAC addresses

- pyasic/miners/miner_factory.py
If a miner doesn't return a VERSION field, then _parse_type_from_version fails and halts. Added a check to return None in this case (resulting in Unknown miner). This occurs to some Whatsminers when they are placed in suspend.
> Add a check in _parse_type_from_version

- pyasic/data/__init__.py
- pyasic/load/__init__.py
- pyasic/miners/antminer/hiveon/X9/T9.py
this way it's easier for other tools like HomeAssistant to understand if the temperature is really negative or not available
HomeAssistant for example shows `Unknown` when the variable is `None`, which is nicer than `-1`
> use `None` instead of `-1` for temps and wattages

- pyasic/API/btminer.py
Previously, pre_power_on would always raise an APIError.
> Fix btminer pre_power_on

- pyasic/web/epic.py
Sorry for this being missed, as we made that one change to respect the ignore_errors.
I might not have explained the API behaviour:
The ePIC REST API will always return. If the data was available it will return with the requested data, if for some reason internally there was a "Lock" on the data or it was currently being updated, the API will return with a "result: false" and an indication of what data was not available. 
In this scenario, 9.999/10 times the solution is just to re-request the data, which is handled in this case. 
Acknowledging this as a APIError seems to crash pyasic-web, so my proposed solution is to make this a "ePIC Error" type, which will just retry the fetch based on the retry count. That should cover all cases
> hotfix: fix epic api error handling

- pyasic/config/__init__.py
- pyasic/config/fans.py
- pyasic/config/mining.py
- pyasic/config/pools.py
- pyasic/config/temperature.py
- pyasic/data/__init__.py
- pyasic/miners/backends/bosminer.py
- pyasic/miners/backends/epic.py
- pyasic/web/bosminer/__init__.py
- pyasic/web/bosminer/proto/braiins/bos/v1/__init__.py
Part 1 of 2. Partially closes https://github.com/UpstreamData/pyasic/issues/80 but currently only handles the get_config side. Want to break this up into two parts + prepare for changes in the pipeline for further configuration options.
Let me know if this tracks with the current methodology, then can continue with the send_config side.
> add MinerConfig support for ePIC UMC

- pyasic/miners/backends/vnish.py
Update backend vnish.py
Vnish miner view:
1) Before fix - `wattage` and `wattage_limit` metrics in different dimensions
2) After fix - `wattage` and `wattage_limit` metrics in same dimensions
For some other miner providers the metrics are the same dimensions.
Thanks for this project, you made my day!
> Fix vnish wattage dimension

- pyasic/data/pools.py
This PR adds the poolUrl dataclass to pools.py which was suggested in PR #145 @b-rowan and here are the changes made: 
-  Created a `Scheme` Enum with `STRATUM_V1` and `STRATUM_V2` variants.
-  Defined the `PoolUrl` dataclass with `scheme`, `host`, `port`, and an optional `pubkey`.
-  Updated `PoolMetrics` to include a `PoolUrl` attribute.
I plan to modify the `_get_pools` methods to parse URLs and populate `poolUrl` instances.
> feat: Add PoolUrl dataclass 

- pyasic/miners/backends/antminer.py
- This PR updates the AntminerModern(BMMiner) _get_pools method to parse URLs. @b-rowan 
- It follows the standard URL/URI spec which handles both Stratum V1 and V2 URLs effectively
> feat: Updated BMMiner _get_pools method to include PoolUrl dataclass.

- pyasic/miners/backends/epic.py
- pyasic/web/epic.py
Add firmware upgrade functionality for ePIC miners
- Implement `upgrade_firmware` method in `pyasic/miners/backends/epic.py`
- Allows upgrading firmware with options to keep settings
- Enhance `system_update` method in `pyasic/web/epic.py`
- Calculates SHA256 checksum for firmware file
- Prepares multipart/form-data request for firmware upload
- Sends command to update system firmware
- Update `send_command` method to handle form data and retries
- Supports both POST and GET requests
- Includes error handling and retries for failed attempts
Reference:  https://app.swaggerhub.com/apis/ePIC-Blockchain/umc_api/0.50.1#/post/update_system
> feat: Add update firmware for ePIC miner

- poetry.lock
- pyasic/miners/backends/braiins_os.py
- pyproject.toml
The tomli libraries seem to be the preferred way to handle toml when the native python tomllib is not available.
> Use builtin tomllib where possible and tomli{-w} where not.

- pyasic/miners/backends/braiins_os.py
Ran into this issue a few times when the miner was stuck in a bad state with no active pool. BraiinsOS would basically not include `alive` which then threw a `KeyError`.
> Fix issue with BraiinsOS pool health check failing

- pyasic/data/__init__.py
- pyasic/data/pools.py
When calling `as_json()`on `MinerData`containing a Scheme attribute (like BOS+ miners), the Scheme enum can't get serialized, resulting in this error:
`TypeError: Object of type Scheme is not JSON serializable`
Adding
`def __json__(self):
return self.value`
To the Scheme class will allow it to be converted to JSON.
> add json serialization to the Scheme class

- pyasic/miners/backends/braiins_os.py
In `BOSer`, it looks like there was a copy/paste error where `rpc` attribute was missing and  `web` was duplicated
> Fix BOSer rpc

- pyasic/config/__init__.py
- pyasic/config/mining/__init__.py
- pyasic/config/mining/presets.py
- pyasic/miners/backends/vnish.py
- pyasic/miners/base.py
Adds support for mining mode presets (used by vnish and luxos mainly), as well as a flag, `supports_presets` to check against.  Presets will be included in the config, including available presets, so that they can be selected from and sent to the miner.
Hopefully a partial prefix to #245.
> feature: add support for mining presets

- pyasic/miners/backends/vnish.py
- pyasic/web/vnish.py
I want to be able to change power for vnish miner using the power slider in [hass-miner](https://github.com/Schnitzel/hass-miner). To do that, `set_power_limit` needs to be implemented in pyasic.
Notes
- Setting power with vnish only works with tuned values. If you call the method with an untuned value, the power doesn't change. It will return the same response (i.e., `{"restart_required":false,"reboot_required":false}`)
- The backend confirms that the power change is successful by getting the updated settings and checking that `updated_settings["miner"]["overclock"]["preset"]` has the desired wattage.
- In the backend, I tried to handle error-handling similarly to how it's done in [BOSMiner](https://github.com/UpstreamData/pyasic/blob/master/pyasic/miners/backends/braiins_os.py#L229) and …
> feature: set power limit for vnish

- pyasic/miners/backends/hammer.py
- pyasic/miners/hammer/blackminer/DX/D10.py
- pyasic/miners/volcminer/blackminer/DX/D1.py
Keep the hashrates consistent across the API and the sticker_hashrate
> fix: change sticker hashrate to GH for Hammer and VolcMiner

- pyasic/miners/backends/hammer.py
- tests/miners_tests/backends_tests/hammer_tests/version_2023_05_28.py
Fix Hammer test. Test was failing due to HR being returned as GH, which when rounded lost precision
> fix hammer test, enforce default hr unit

- pyasic/miners/backends/luxminer.py
- pyasic/rpc/luxminer.py
This PR adds `set_power_limit` functionality for luxos, which already exists for [braiins](https://github.com/UpstreamData/pyasic/blob/97c20dae0a3ad1effacaaf32e65b1492a76b9fff/pyasic/miners/backends/braiins_os.py#L221) and [vnish](https://github.com/UpstreamData/pyasic/pull/245).  This PR uses [mining mode presets](https://github.com/UpstreamData/pyasic/pull/262) to set power.
Notes
- In luxos, the profile cannot be changed if [ATM (Advanced Thermal Management)](https://docs.luxor.tech/firmware/features/atmsettings) is enabled. Logic was added to check if ATM is enabled, disable it, and re-enable it after changing profile.
- Added `atm`, `atmset` methods to rpc
> feature: set power limit for luxos

- pyasic/miners/factory.py
Fixes  #270
> Just need to combine them in miners.antminer.vnish.x19, make sure they're imported in that init (it's all star inputs all the way up from there), then add the model string in all caps to the MINER_CLASSES dict in factory.
I realized that I only needed to update MINER_CLASSES dict in factory and didn't need to add anything to `miners.antminer.vnish.x19` since is the miner is a `VNishS19jPro`
I saw that  [`ANTMINER S19J PRO BB`](https://github.com/UpstreamData/pyasic/commit/c19945bb82dd99b64cefcddfa1329520d4ff47df) had been added similarly in the past
I confirmed that this works by re-running my previous code (`await get_miner("192.168.1.184")`), and the warning no longer appears.
> feature: add support for Vnish S19j Pro A

- pyasic/miners/backends/luxminer.py
- pyasic/rpc/luxminer.py
- pyasic/web/auradine.py
When I build the docs locally (`poetry run mkdocs serve`), there are a couple warnings. This PR fixes those issues.
```
INFO    -  Building documentation...
INFO    -  Cleaning site directory
WARNING -  griffe: pyasic/rpc/luxminer.py:578: No type or
annotation for parameter 'session_id'
WARNING -  griffe: pyasic/rpc/luxminer.py:578: Parameter
'session_id' does not appear in the function
signature
WARNING -  griffe: pyasic/rpc/luxminer.py:851: No type or
annotation for returned value 1
WARNING -  griffe: pyasic/web/auradine.py:275: No type or
annotation for parameter '**kwargs'
WARNING -  griffe: pyasic/web/auradine.py:294: No type or
annotation for parameter '**kwargs'
INFO    -  Documentation built in 12.09 seconds
INFO    -  [04:44:25] Watching paths for changes: 'docs',
'mkdocs.yml' …
```
> docs: fix issues for docs warnings

- pyasic/config/mining/__init__.py
- pyasic/miners/backends/luxminer.py
This PR adds `_get_wattage_limit` method for Luxos by getting the wattage from the active profile (added in #262)
This method is needed to add the ability to set the power limit in [hass-miner](https://github.com/Schnitzel/hass-miner) for Luxos miners.
> feature: add _get_wattage_limit for luxos

- poetry.lock
- pyproject.toml
Used directly [here](https://github.com/UpstreamData/pyasic/blob/v0.70.5/pyasic/rpc/btminer.py#L29).
> Add cryptography direct dependency

- pyasic/miners/factory.py
A device was crashing constantly and I couldn't figure out why. It turns out that `_socket_ping` was hanging indefinitely as  `asyncio.wait_for` was raising `asyncio.TimeoutError` indefinitely, causing the connection to never get released and since I was running `get_miner` every hour it would eventually run out of sockets.
This patch adds a max number of timeouts before we exit out.
> Don't timeout forever on _socket_ping

- pyasic/miners/backends/luxminer.py
Previous PRs added functionality for Luxos to enable set_power_limit slider in [hass-miner](https://github.com/Schnitzel/hass-miner) (works for Braiins but not Luxos).
- [mining presets](https://github.com/UpstreamData/pyasic/pull/262)
- [`set_power_limit`](https://github.com/UpstreamData/pyasic/pull/267)
- [`get_wattage_limit`](https://github.com/UpstreamData/pyasic/pull/277)
hass-miner checks if [ `supports_autotuning` is True](https://github.com/Schnitzel/hass-miner/blob/2315cc21e0fcd00f75d42c1ddfcfb21c9e4d5d4b/custom_components/miner/number.py#L57) to set the power limit. This value is set to True for Braiins and Vnish. This PR sets it to True for Luxos
> feat: set supports_autotuning to True for luxminer

- pyasic/miners/backends/luxminer.py
[Previous PR](https://github.com/UpstreamData/pyasic/pull/267) added `set_power_limit` for Luxos by adding `atmset` to rpc.
This PR fixes bug in `set_power_limit` by passing `enabled` param as bool (instead of str)
> fix: pass atmset param as bool in Luxos

- docs/miners/avalonminer/nano.md
- docs/miners/supported_types.md
- pyasic/device/models.py
- pyasic/miners/avalonminer/cgminer/nano/__init__.py
- pyasic/miners/avalonminer/cgminer/nano/nano3.py
- pyasic/miners/device/models/avalonminer/nano/__init__.py
- pyasic/miners/device/models/avalonminer/nano/nano3.py
- pyasic/miners/factory.py
- pyproject.toml
Adds support for Avalon Nano3s.
Example output:
> feature: Add Support for Avalon Nano 3s

- pyasic/miners/avalonminer/cgminer/nano/nano3.py
- pyproject.toml
**Efficiency Fix**
The efficiency field was not being populated from the get_data call. After investigating I found that the _get_wattage WALLPOWER field that is referenced in avalonminer.py is not populated by the nano3s. Reviewing the source for the avalon's web gui I found that the wallpower is actually being pulled from the power_info[6] field as shown [here](https://github.com/Canaan-Creative/Avalon_Nano3s/blob/04c84d312a4e38c1efa437b086bbcb297749e77a/cg_miner/cgminer/driver-avalon.c#L1228). The documentation for this field is described [here](https://github.com/Canaan-Creative/avalon10-docs/blob/master/Universal%20API/Avalon%20A10%20API%20manual-EN.md#29--query-hash-power-state).
**Hashrate Fix**
The hashrate returned by this library was not matching what was showing on the nano3 …
> fix: nano3s Efficiency and Hashrate Fixes

- pyasic/web/espminer.py
Adds retry logic and get timeout support for espminer send_command. Looked at the web/goldshell.py/send_command as an example. The lucky miner lv08 sometimes gets timeout errors on get_data, this is an attempt to resolve that.
> Retry and Timeout Changes for espminer

- .gitignore
- docs/miners/goldshell/Byte.md
- docs/miners/supported_types.md
- mkdocs.yml
- pyasic/config/__init__.py
- pyasic/config/pools.py
- pyasic/device/algorithm/__init__.py
- pyasic/device/algorithm/hashrate/__init__.py
- pyasic/device/algorithm/hashrate/unit/__init__.py
- pyasic/device/algorithm/hashrate/unit/zksnark.py
- pyasic/device/algorithm/hashrate/zksnark.py
- pyasic/device/algorithm/zksnark.py
- pyasic/device/models.py
- pyasic/miners/device/models/goldshell/Byte/Byte.py
- pyasic/miners/device/models/goldshell/Byte/__init__.py
- pyasic/miners/device/models/goldshell/__init__.py
- pyasic/miners/factory.py
- pyasic/miners/goldshell/bfgminer/Byte/Byte.py
- pyasic/miners/goldshell/bfgminer/Byte/__init__.py
This adds support for the Goldshell Byte. The Byte is unique in that it supports 0 to 2 cards that can have different algorithms. Currently it supports Scrypt and zkSNARK (Aleo) algorithms. Each card has its own unique number of chips, so we need to do some various calculations based on which card we are looking at. Note that when there are no cards attached various apis are not available, so we don't get all of the base data. When there is one of each card type it uses the default Generic algo.
> Goldshell Byte Support

- pyasic/miners/avalonminer/cgminer/nano/nano3.py
- pyasic/miners/backends/avalonminer.py
This PR fixes issues introduced by [this commit](https://github.com/PixelByProxy/pyasic/commit/5457ae6cd5618ef8f2ffa0ed4aa5b27715e24a6c) for adding Avalon Q support. The main issues were:
1. _get_hashboards was not handling the TypeError so it would not fall back to the old logic if the value was not an array.
2. On the Nano3s the dictionary values are "TMax" and "TAvg" rather than "Tmax" and Tavg". Updated to handle both cases.
3. In CGMinerAvalonNano3s, the parse_estats was not using the correct value. It was passing in the string instead of the object.
> Avalon Nano3s Fixes

- pyasic/rpc/base.py
- pyasic/web/auradine.py
- pyasic/web/espminer.py
Multiple multicommand methods were double-awaiting tasks - first via asyncio.gather() with return_exceptions=True, then calling .result() on the same tasks. This caused ConnectionResetError and other exceptions when connections were lost.
Changed to properly use the results from gather() instead of calling .result() on completed tasks, preventing exceptions from being raised after they were already caught.
Fixed in:
- pyasic/rpc/base.py:144 - RPC _send_split_multicommand
- pyasic/web/espminer.py:79 - ESPMiner multicommand
- pyasic/web/auradine.py:149 - Auradine multicommand
> Fix race conditions in RPC and web API multicommand methods
