network/__init__.py
network/net_range.py

I was looking to provide a list of known IPs to the MinerFactory, so it doesn't have to scan a subnet, and it's less bulky than a list of singleton ranges.

Allow MinerFactory to take a list of discrete IPs

---

pyasic/miners/backends/vnish.py

Update vnish.py. Fix data locations according to the method arguments

Fix VNish get_hashrate and get_fans errors

---

pyasic/config/__init__.py
pyasic/config/fans.py
pyasic/config/mining.py
pyasic/config/pools.py
pyasic/config/temperature.py
pyasic/miners/backends/epic.py
pyasic/miners/base.py
pyasic/web/epic.py
tests/config_tests/__init__.py

Add ePIC send_config and config.as_epic

---

pyasic/config/pools.py
pyasic/miners/backends/epic.py
pyasic/web/epic.py

Quick and dirty fixes to enabled the send_config for ePIC UMC. Feel free to rework @UpstreamData

fix send_config for ePIC

---

pyasic/ssh/antminer.py
pyasic/ssh/braiins_os.py

Partial fix https://github.com/UpstreamData/pyasic/issues/8
Add documentation for `ssh`

docs: Add documentation for `ssh`

---

pyasic/config/__init__.py

Partial fix #8 
Fixes #124
Add documentation for `config`

docs: Add documentation for `config`

---

pyasic/web/antminer.py
pyasic/web/auradine.py

partially fixes issue #8 
Added docstring for `web/antminer` and `web/auradine`

doc: add docstring for antminer and auradine in web

---

tests/rpc_tests/__init__.py

Partial fixes #8 
Added tests in rpc_tests for TestGCMinerRPCAPI

Add tests in rpc_tests

---

tests/config_tests/fans.py

Partial Fixes #8 
Added tests in config_tests

Add tests in config_tests

---

pyasic/config/base.py
pyasic/config/mining.py
pyasic/config/temperature.py
pyasic/data/__init__.py
pyasic/miners/backends/epic.py
pyasic/miners/base.py
pyasic/miners/data.py
pyasic/web/epic.py

- Add Output Voltage of the PSU to MinerData
- Fix ePIC PTune send_config
**### Add some additional ePIC UMC features:**
- Add Vopt Throttle Step and Min Throttle Target
- Add Shutdown Temp and Critical Temp
- Add HB serial numbers

feat: add additional ePIC UMC features, add Output Voltage to MinerData

---

pyasic/data/__init__.py
pyasic/miners/backends/antminer.py
pyasic/miners/base.py
pyasic/miners/data.py

This method creates the _get_pools  function for the antminer type. @b-rowan

Create _get_pools method for Antminer backend class

---

pyasic/config/__init__.py
pyasic/config/scaling.py
tests/config_tests/__init__.py

- Add hashrate scaling to config.
- Rename `power_scaling` and like instances to just `scaling`

feature: add hashrate scaling to config

---

pyasic/miners/backends/braiins_os.py

- This PR adds the` _get_pools` method to BOSMiner backend class in `brains_os.py` @b-rowan

pools: Add _get_pools method to BOSMiner backend class. 

---

pyasic/miners/backends/braiins_os.py

- This PR updates the BOSMiner(BraiinsOSFirmware) _get_pools method to parse URLs. @b-rowan
- It follows the standard URL/URI spec which handles both Stratum V1 and V2 URLs effectively

feat: Updated BOSMiner _get_pools method to include PoolUrl dataclass.

---

pyasic/miners/backends/luxminer.py

This PR adds the ` _get_pools ` method to luxminer. @b-rowan

feat: Add _get_pools method to Luxminer

---

pyasic/miners/antminer/vnish/X19/S19.py
pyasic/miners/antminer/vnish/X19/__init__.py
pyasic/miners/backends/luxminer.py
pyasic/miners/factory.py
pyasic/web/epic.py

Adds support for S19 Pro Hydro running vnish.  Also some minor bug fixes.  Closes #169.

feature: add support for Vnish S19 Pro Hydro.

---

pyasic/miners/backends/innosilicon.py

This PR adds _get_pools method for Innosilicon miners (CGMiner). @b-rowan 
Attention: I will like you to take a look at line 119. `MinerConfig.from_inno()` was expecting a `list` but got a `dict` instead, so I converted it into a `list`.

feat: Add _get_pools method for Innosilicon miners (CGMiner). 

---

README.md

Also see [issue #106](https://github.com/UpstreamData/pyasic/issues/106)  for details

documentation: Changed settings key in readme to reflect default values

---

pyasic/miners/backends/braiins_os.py
pyasic/web/braiins_os/boser.py

- This PR adds the _get_pools method to BOSer backend class in brains_os.py @b-rowan

feat: Add _get_pools method to BOSer backend class. 

---

pyasic/miners/backends/marathon.py
pyasic/rpc/marathon.py

feature: add mara rpc API.

---

pyasic/settings/__init__.py

Remove horribly broken SO_LINGER socket options

---

pyasic/miners/backends/cgminer.py

This `PR` adds _get_pools method for CGMiner (StockFirmware) @b-rowan

feat: Add _get_pools method for CGMiner (StockFirmware)

---

docs/generate_miners.py
docs/miners/antminer/X19.md
docs/miners/antminer/X21.md
docs/miners/iceriver/KSX.md
docs/miners/supported_types.md
pyasic/device/models.py
pyasic/miners/backends/__init__.py
pyasic/miners/backends/iceriver.py
pyasic/miners/device/models/__init__.py
pyasic/miners/device/models/iceriver/KSX/KS2.py
pyasic/miners/device/models/iceriver/KSX/__init__.py
pyasic/miners/device/models/iceriver/__init__.py
pyasic/miners/factory.py
pyasic/miners/iceriver/__init__.py
pyasic/miners/iceriver/iceminer/KSX/KS2.py
pyasic/miners/iceriver/iceminer/KSX/__init__.py
pyasic/miners/iceriver/iceminer/__init__.py
pyasic/settings/__init__.py
pyasic/web/__init__.py
pyasic/web/iceriver.py

Adds iceriver support, with some basic functions.

feature: Add iceriver support

---

pyasic/miners/backends/luxminer.py
pyasic/rpc/luxminer.py

This PR aims to add update firmware functionality for LuxOS Miner.

feat: Add update firmware for LuxOS Miner

---

pyasic/miners/backends/marathon.py

This PR adds `_get_pools` method to marathon miner @b-rowan

feat: add _get_pools method for marathon miner

---

pyasic/miners/backends/btminer.py

This PR adds `_get_pools`  method to BTMiner(StockFirmware). @b-rowan

feat: Add _get_pools method for BTMiner(StockFirmware)

---

pyasic/miners/backends/bfgminer.py

This PR adds `_get_pools` method to BFGMiner(StockFirmware) @b-rowan

feat: Add _get_pools method for BFGMiner(StockFirmware) 

---

poetry.lock
pyasic/config/mining/__init__.py
pyasic/config/pools.py
pyasic/miners/backends/braiins_os.py
pyasic/web/braiins_os/better_monkey.py
pyasic/web/braiins_os/boser.py
pyasic/web/braiins_os/proto/braiins/bos/__init__.py
pyasic/web/braiins_os/proto/braiins/bos/v1/__init__.py
pyproject.toml

Update betterproto and regenerate protoc files

---

pyasic/config/__init__.py
pyasic/config/base.py
pyasic/config/fans.py
pyasic/config/mining/__init__.py
pyasic/config/pools.py
pyasic/config/temperature.py
pyasic/miners/backends/luxminer.py
pyasic/miners/factory.py
pyasic/rpc/luxminer.py

Adding some fixes and features for LuxOS miners, such as config.

feature: LuxOS fixes and updates

---

pyasic/miners/backends/bmminer.py

This PR adds the _get_pools method to Bmminer @b-rowan.

feat: Add _get_pools method for Bmminer.

---

pyasic/miners/factory.py

Just trying to keep the logs in my client script quieter / cleaner.
...or can switch it to a `logger.debug()` statement if it's still needed.

trivial debugging cleanup

---

pyasic/data/__init__.py

fix: update data.env_temp type to float

---

pyasic/config/__init__.py
pyasic/config/mining/__init__.py
pyasic/config/mining/presets.py
pyasic/miners/backends/luxminer.py

https://github.com/UpstreamData/pyasic/pull/246 added mining mode presets for Vnish so they could be included in config and sent to the miner. These presets made it possible to set the power limit (https://github.com/UpstreamData/pyasic/pull/245)
This PR adds mining mode presets for Luxos.  `set_power_limit` for Luxos will be implemented in a future PR

feature: add mining presets for luxos

---

pyasic/miners/backends/bitaxe.py

Add expected hashrate using current API. PR for this calculated on the miner side is submitted however this will allow backwards compatibility with any FW version. 
In future can update to use new calculated value and fall back to manual calculation.

feat: add expected_hashrate for bitaxe devices

---

docs/miners/antminer/X21.md
docs/miners/supported_types.md
pyasic/miners/antminer/vnish/X21/T21.py
pyasic/miners/factory.py

Fixes #272 
I followed the logic from https://github.com/UpstreamData/pyasic/commit/8e15b00e704f526e06728b9d55ab95b250dee04e to figure out all the changes needed to create `VNishT21`.
Documentation was also updated but not verified locally. Are there instructions somewhere on how to build the docs?

feature: add support for Vnish T21

---

README.md

Added instructions to readme for building docs locally

docs: add instructions for building docs locally

---

pyasic/settings/__init__.py

fix hammer default password

---

pyasic/miners/backends/avalonminer.py

add power limit to avalon nano

feat: add powerlimit to avalon nano

---

pyasic/config/mining/__init__.py

bug: fix set_dps configuration to handle power target parameters correctly

---

docs/miners/antminer/X21.md
docs/miners/supported_types.md
pyasic/data/boards.py
pyasic/device/models.py
pyasic/miners/antminer/bmminer/X21/S21.py
pyasic/miners/antminer/bmminer/X21/__init__.py
pyasic/miners/backends/antminer.py
pyasic/miners/backends/bmminer.py
pyasic/miners/device/models/antminer/X21/S21.py
pyasic/miners/device/models/antminer/X21/__init__.py
pyasic/miners/factory.py

- add inlet_temp, outlet_temp for hydro asics hashboards 
- add S21+ hydro definition
- fix: add a zero safe values for hashboard temp and chip_temp if we have to divide by zero
- add temperature data handling features for S21+ hyd
- generate documentation

feature: add support for S21+ hydro

---

pyasic/data/__init__.py

Fix efficiency calculation and add computed fields

---

pyasic/data/__init__.py

Fix efficiency_fract property to correctly return computed value
